# DESARROLLO DE LA TAREA (APLICACION DE REDES NEURONALES)

In [15]:
import numpy as np
import math

__Entrada, pesos y target__

In [39]:
target=np.array([1.0,0.0,0.0])
w1=np.around(np.random.rand(3,3),2)
w2=np.around(np.random.rand(3,3),2)
w3=np.around(np.random.rand(3,3),2)
entrada=np.array([0.1,0.2,0.7])
b=np.array([1.0,1.0,1.0])
w=np.array([w1,w2,w3])

__Funciones a utilizar__

In [17]:
def calcular_salida(p,w,b):
    r=p.dot(w)+b
    return r

In [18]:
def relu(p):
    return np.maximum(0,p)

In [33]:
def sigmoid(p):
    return 1 / (1+np.exp(-p))

In [20]:
# Funcion Softmax
def softmax(p):
	e = np.exp(p)
	return e / e.sum()

In [21]:
#Funcion para obtener el valor de la entropia cruzada
def cross_entropy (predictions, targets): 
    predictions = np.clip(predictions, 1e-10, 1. -(1e-10)) 
    N = predictions.shape[0]
    ce = -np.sum(targets*np.log(predictions+1e-9))/N
    return ce

__Funciones derivadas__

In [22]:
def deriv_sigmoid(p):
     return sigmoid(p)*(1-sigmoid(p))

In [23]:
def deriv_relu(p, alpha=.01):
     return np.array ([1 if i >= 0 else alpha for i in p])

In [24]:
def deriv_softmax(p):
	return (np.exp(p[0])*(np.exp(p[1])+ np.exp(p[2])))/(np.exp(p[0])+np.exp(p[1])+ np.exp(p[2]))**2

In [25]:
def deriv_entropy(predictions,targets):
    return (-1)*np.sum([predictions[i]*1/targets[i] + (1-predictions[i])*(1/(1-targets[i])) for i in range(0,3)])

# PRIMERA CAPA

In [31]:
salida_capa1=calcular_salida(entrada,w1,b)

In [30]:
#aplicandoRelu
salida_capa1=relu(salida_capa1)
salida_capa1

array([1.366, 1.561, 1.682])

# Segunda Capa

In [34]:
entrada_capa2=salida_capa1
salida_capa2=calcular_salida(entrada_capa2,w2,b)
salida_capa2=sigmoid(salida_capa2)
salida_capa2

array([0.96975698, 0.98426659, 0.94174914])

# Tercera Capa

In [35]:
entrada_capa3=salida_capa2
salida_capa3=calcular_salida(entrada_capa3,w3,b)
salida_capa3=softmax(salida_capa3)
salida_capa3

array([0.24640923, 0.55560647, 0.1979843 ])

# Usando la entropia cruzada para evaluar el error

In [37]:
cross_entropy (salida_capa3, target)


0.4669205262864546