# DESARROLLO DE LA TAREA (APLICACION DE REDES NEURONALES)

__Primera Capa__

In [75]:
import numpy as np
import math

In [76]:
def calcular_salida(p,w,b):
    r=p.dot(w)+b
    return r

In [77]:
p=np.array([0.1,0.2,0.7])
w=np.array([[0.1,0.4,0.3],[0.3,0.7,0.7],[0.5,0.2,0.9]])
b=np.array([1.0,1.0,1.0])
p_capa1=calcular_salida(p,w,b)


__Segunda Capa__

In [84]:
p=p_capa1
w=np.array([[0.2,0.1,0.4],[0.3,0.4,0.1],[0.7,0.1,0.2]])
b=np.array([1.0,1.0,1.0])
p=calcular_salida(p,w,b)
p

array([2.94, 1.85, 2.06])

In [85]:
def sigmoid(p):
    return 1 / (1+np.exp(-x))
p_sigmoid=sigmoid(p)

In [86]:
p_sigmoid


array([0.80533842, 0.78918171, 0.85814894])

__Tercera Capa__

In [87]:
p=p_sigmoid
w=np.array([[0.5,0.3,0.1],[0.6,0.4,0.8],[0.1,0.9,0.6]])
b=np.array([1.0,1.0,1.0])
p=calcular_salida(p,w,b)
p 

array([1.96199313, 2.32960825, 2.22676857])

In [88]:
# Funcion Softmax
def softmax(p):
	e = np.exp(p)
	return e / e.sum()
p_softmax=softmax(p)

In [89]:
p_softmax

array([0.26684995, 0.38540766, 0.34774239])

**_Usando la entropia cruzada para evaluar el error_**

In [91]:
targets=np.array([1.0,0.0,0.0])

In [96]:
#Funcion para obtener el valor de la entropia cruzada
def cross_entropy (predictions, targets): 
    predictions = np.clip(predictions, 1e-10, 1. -(1e-10)) 
    N = predictions.shape[0]
    ce = -np.sum(targets*np.log(predictions+1e-9))/N
    return ce

    Con SOFTMAX

In [97]:
cross_entropy (p_softmax, targets)

0.4403562554971829

    CON EL RESULTADO DE LA SEGUNDA CAPA

In [98]:
cross_entropy (p_sigmoid, targets)

0.07216423186944051